#!/bin/sh
# We need to assume 1 compiler per platform.
# There is no other way around this.
if [ ! "$SCRAM_ARCH" ]
then
    osarch=`@CMS_PREFIX@/common/cmsos`
    compilerv=gcc820
    case $osarch in
        osx*)         compilerv=gcc$(gcc -dumpversion | sed 's|\.||g') ;;
        fc18_*)       compilerv=gcc491 ;;
        fc19_armv7hl) compilerv=gcc481 ;;
        fc19_aarch64) compilerv=gcc490 ;;
        fc22_ppc64le) compilerv=gcc530 ;;
        fc24_ppc64le) compilerv=gcc620 ;;
        slc5_ia32)    compilerv=gcc434 ;;
        slc5_*)       compilerv=gcc481 ;;
        slc6_*)       compilerv=gcc700 ;;
        slc7_*)       compilerv=gcc820 ;;
        cc8_* )       compilerv=gcc8   ;;
        *)            compilerv=gcc820 ;;
    esac
    echo ${osarch}_${compilerv}
else
    echo $SCRAM_ARCH
fi
