#!/bin/bash -e
cms_basedir="@CMS_PREFIX@"
CRAB_PKG=$(basename $0)
if [ "${SCRAMRT_SET}" = "" ] ; then
  >&2 echo "Error: Please set SCRAM/CMSSW runtime environment before running crab"
  exit 1
fi
export SCRAM_PROJECT_BASE="${CMSSW_BASE}"
CMSOS=$(${cms_basedir}/common/cmsos)
if [ "${CRAB_PKG}" = "crab-prod" ] ; then CRAB_PKG="crab" ; fi
if [ "${CRAB_VERSION}" = "" ] ; then
  CRAB_VERSION=$(ls -d ${cms_basedir}/${CMSOS}_gcc*/cms/${CRAB_PKG}/*/etc/profile.d/init.sh | sed "s|^.*/cms/${CRAB_PKG}/||;s|/.*||" | sort | tail -1)
fi
CRAB_DIR=$(ls -d ${cms_basedir}/${CMSOS}_gcc*/cms/${CRAB_PKG}/${CRAB_VERSION}/etc/profile.d/init.sh | sed 's|/etc/profile.d/init.sh$||' | sort | tail -1)
export CRAB_VERSION=${CRAB_VERSION}

## If it is a submit command run the bootstrap script
ERR=0
if [ $(echo "$@" | tr ' ' '\n' | grep 'sub\|submit' | wc -l) -gt 0 ] ; then
  BOOTSTRAP_OUT=$(source ${CRAB_DIR}/etc/profile.d/init.sh >/dev/null 2>&1; ${CRAB_DIR}/bin/crab3bootstrap $@) || ERR=$?
  if [ $ERR -ne 0 ]; then
    echo "$BOOTSTRAP_OUT"
    exit $ERR
  fi
  ## The submit command will know what to do if this variable is set!
  ## See TODO: add link to an hypothetical twiki
  export CRAB3_BOOTSTRAP_DIR="$BOOTSTRAP_OUT"
fi

eval `scram unset -sh`
source ${CRAB_DIR}/etc/profile.d/init.sh

## Execute the client command in a pure COMP environment
${CRAB_DIR}/bin/crab "$@" || ERR=$?

## Remove the temporary direcotry, but only if we run the bootstrap script
[ -z "$CRAB3_BOOTSTRAP_DIR" ] || rm -rf "$CRAB3_BOOTSTRAP_DIR"

exit $ERR
